Repository glotzerlab/hoomd-blue, pull requests merged in 2021-07, with the labels that each got.

#1057 Fix the ThermdynamicQuantities.volume property
  hoomd/md/ComputeThermo.h
  hoomd/md/compute.py
  hoomd/md/pytest/test_thermo.py
Labels: validate

#946 Convert Mueller plathe flow to v3 API
  .pre-commit-config.yaml
  hoomd/md/CMakeLists.txt
  hoomd/md/MuellerPlatheFlow.cc
  hoomd/md/MuellerPlatheFlow.h
  hoomd/md/MuellerPlatheFlowEnum.h
  hoomd/md/MuellerPlatheFlowGPU.cc
  hoomd/md/MuellerPlatheFlowGPU.cu
  hoomd/md/MuellerPlatheFlowGPU.cuh
  hoomd/md/MuellerPlatheFlowGPU.h
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_reverse_perturbation_flow.py
  hoomd/md/update.py
  setup.cfg
  sphinx-doc/module-md-update.rst
  sphinx-doc/package-md.rst
Labels: validate

#1059 Fix debug mode tests
  hoomd/ExecutionConfiguration.h
  hoomd/md/NeighborList.cc
  hoomd/md/NeighborList.h
Labels: validate

#1061 Fix typos in Rigid docstrings
  hoomd/md/constrain.py
Labels: documentation, validate

#1028 New potential with Mie parameters and SLJ parameters
  hoomd/md/AllDriverPotentialPairGPU.cuh
  hoomd/md/AllExternalPotentials.h
  hoomd/md/AllPairPotentials.h
  hoomd/md/CMakeLists.txt
  hoomd/md/EvaluatorPairExpandedMie.h
  hoomd/md/ExpandedMieDriverPotentialPairGPU.cu
  hoomd/md/module-md.cc
  hoomd/md/pair/__init__.py
  hoomd/md/pair/pair.py
  hoomd/md/pytest/forces_and_energies.json
  hoomd/md/pytest/test_potential.py
  sphinx-doc/module-md-pair.rst
Labels: validate

#1062 Implement constrain.Distance
  .pre-commit-config.yaml
  hoomd.code-workspace
  hoomd/md/ForceDistanceConstraint.cc
  hoomd/md/ForceDistanceConstraint.h
  hoomd/md/constrain.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_constrain_distance.py
  setup.cfg
  sphinx-doc/module-md-constrain.rst
Labels: validate

#965 Convert Table Potential to v3 API
  hoomd/ManagedArray.h
  hoomd/data/parameterdicts.py
  hoomd/data/typeconverter.py
  hoomd/md/AllDriverPotentialPairGPU.cuh
  hoomd/md/AllPairPotentials.h
  hoomd/md/CMakeLists.txt
  hoomd/md/EvaluatorPairBuckingham.h
  hoomd/md/EvaluatorPairDLVO.h
  hoomd/md/EvaluatorPairDPDLJThermo.h
  hoomd/md/EvaluatorPairDPDThermo.h
  hoomd/md/EvaluatorPairEwald.h
  hoomd/md/EvaluatorPairExpandedMie.h
  hoomd/md/EvaluatorPairForceShiftedLJ.h
  hoomd/md/EvaluatorPairFourier.h
  hoomd/md/EvaluatorPairGB.h
  hoomd/md/EvaluatorPairGauss.h
  hoomd/md/EvaluatorPairLJ.h
  hoomd/md/EvaluatorPairLJ0804.h
  hoomd/md/EvaluatorPairLJ1208.h
  hoomd/md/EvaluatorPairMie.h
  hoomd/md/EvaluatorPairMoliere.h
  hoomd/md/EvaluatorPairMorse.h
  hoomd/md/EvaluatorPairOPP.h
  hoomd/md/EvaluatorPairReactionField.h
  hoomd/md/EvaluatorPairSLJ.h
  hoomd/md/EvaluatorPairTWF.h
  hoomd/md/EvaluatorPairTable.h
  hoomd/md/EvaluatorPairYukawa.h
  hoomd/md/EvaluatorPairZBL.h
  hoomd/md/PotentialPair.h
  hoomd/md/PotentialPairDPDThermo.h
  hoomd/md/PotentialPairDPDThermoGPU.h
  hoomd/md/PotentialPairGPU.cuh
  hoomd/md/PotentialPairGPU.h
  hoomd/md/TableDriverPotentialPairGPU.cu
  hoomd/md/TablePotential.cc
  hoomd/md/TablePotential.h
  hoomd/md/TablePotentialGPU.cc
  hoomd/md/TablePotentialGPU.cu
  hoomd/md/TablePotentialGPU.cuh
  hoomd/md/TablePotentialGPU.h
  hoomd/md/module-md.cc
  hoomd/md/pair/__init__.py
  hoomd/md/pair/pair.py
  hoomd/md/pytest/forces_and_energies.json
  hoomd/md/pytest/test_potential.py
  hoomd/md/test/CMakeLists.txt
  hoomd/md/test/test_table_potential.cc
  sphinx-doc/module-md-pair.rst
Labels: validate

#1012 Wrap method for snapshot
  hoomd/SnapshotSystemData.cc
  hoomd/SnapshotSystemData.h
  hoomd/pytest/test_snapshot.py
  hoomd/snapshot.py
  sphinx-doc/credits.rst
Labels: validate

#1069 update cmake-modules to support git worktree
  CMake/git/GetGitRevisionDescription.cmake
  CMake/git/GetGitRevisionDescription.cmake.in
Labels: validate

#1072 More explicit inlcludes
  .github/workflows/release.yml
  .github/workflows/templates/configurations.yml
  .github/workflows/templates/workflow.yml
  .github/workflows/test.yml
  BUILDING.rst
  hoomd/DCDDumpWriter.cc
  hoomd/GSDDumpWriter.cc
  hoomd/md/PotentialPair.h
Labels: release, validate

#1076 Remove manual signal handling
  hoomd/CMakeLists.txt
  hoomd/SignalHandler.cc
  hoomd/SignalHandler.h
  hoomd/System.cc
Labels: validate

#1082 Remove Doxygen documentation
  .vscode/settings.json
  BUILDING.rst
  CMakeLists.txt
  Doxyfile
  doc/CMakeLists.txt
  doc/Doxyfile_dev.in
  doc/dev/DeveloperInfo.doc
  doc/dev/Groups.doc
  doc/dev/MainPage.doc
  doc/dev/doxygen_dummy.h
  sphinx-doc/style.rst
Labels: validate

#1080 Remove write_debug_data
  hoomd/hpmc/pytest/CMakeLists.txt
  hoomd/hpmc/pytest/test_write_debug_data_hpmc.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_write_debug_data_md.py
  hoomd/simulation.py
Labels: validate

#1084 Remove addTypes and related methods
  hoomd/CellListStencil.cc
  hoomd/CellListStencil.h
  hoomd/Communicator.cc
  hoomd/Communicator.h
  hoomd/ParticleData.cc
  hoomd/ParticleData.h
  hoomd/hpmc/IntegratorHPMC.cc
  hoomd/hpmc/IntegratorHPMC.h
  hoomd/hpmc/IntegratorHPMCMono.h
  hoomd/hpmc/IntegratorHPMCMonoGPU.h
  hoomd/hpmc/UpdaterClustersGPU.h
  hoomd/hpmc/UpdaterMuVT.h
  hoomd/jit/PatchEnergyJITUnion.h
  hoomd/jit/PatchEnergyJITUnionGPU.h
  hoomd/md/AnisoPotentialPair.h
  hoomd/md/ForceComposite.cc
  hoomd/md/ForceComposite.h
  hoomd/md/NeighborList.cc
  hoomd/md/NeighborList.h
  hoomd/md/NeighborListGPUTree.cc
  hoomd/md/NeighborListGPUTree.h
  hoomd/md/NeighborListTree.cc
  hoomd/md/NeighborListTree.h
  hoomd/md/PotentialExternal.h
  hoomd/md/PotentialPair.h
  hoomd/md/PotentialTersoff.h
  hoomd/md/TwoStepLangevinBase.cc
  hoomd/md/TwoStepLangevinBase.h
  hoomd/md/test/test_neighborlist.cc
  hoomd/metal/EAMForceCompute.cc
  hoomd/metal/EAMForceCompute.h
  hoomd/test/test_pdata.cc
Labels: validate

#1085 Unify msg_file
  hoomd/Messenger.cc
  hoomd/Messenger.h
  hoomd/communicator.py
  hoomd/device.py
  hoomd/hpmc/update.py
  hoomd/pytest/test_device.py
Labels: validate

#1083 Move filter tests using md to hoomd/md/pytest
  hoomd.code-workspace
  hoomd/__init__.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_filter_md.py
  hoomd/pytest/test_filter.py
Labels: validate
