Repository glotzerlab/hoomd-blue, pull requests merged in 2021-09, with the labels that each got.

#1126 Make LocalSnapshot and Snapshot have equivalent API
  hoomd/data/local_access.py
  hoomd/pytest/test_local_snapshot.py
Labels: validate

#1122 Fix errors compiling with single precision
  hoomd/UpdaterRemoveDrift.h
  hoomd/md/EvaluatorPairLJ0804.h
  hoomd/md/EvaluatorPairLJ1208.h
Labels: validate

#1123 Improve object introspection and autocomplete support
  hoomd/custom/custom_operation.py
  hoomd/operation.py
  hoomd/tune/custom_tuner.py
  hoomd/update/custom_updater.py
  hoomd/write/custom_writer.py
Labels: validate

#1113 Improve MD documentation.
  hoomd/md/angle.py
  hoomd/md/bond.py
  hoomd/md/compute.py
  hoomd/md/constrain.py
  hoomd/md/dihedral.py
  hoomd/md/external/field.py
  hoomd/md/many_body.py
  hoomd/md/pair/aniso.py
  hoomd/md/pair/pair.py
  hoomd/md/special_pair.py
  hoomd/md/wall.py
  sphinx-doc/conf.py
Labels: validate

#1118 Fix Integrator and Neighbor List detaching
  hoomd/data/syncedlist.py
  hoomd/hpmc/integrate.py
  hoomd/hpmc/update.py
  hoomd/md/force.py
  hoomd/md/integrate.py
  hoomd/md/methods/methods.py
  hoomd/md/methods/rattle.py
  hoomd/md/nlist.py
  hoomd/md/pair/pair.py
  hoomd/md/pytest/test_integrate.py
  hoomd/md/pytest/test_nlist.py
  hoomd/md/pytest/test_potential.py
  hoomd/operation.py
  hoomd/operations.py
  hoomd/pytest/test_filter_updater.py
  hoomd/pytest/test_operation.py
  hoomd/pytest/test_syncedlist.py
Labels: validate

#1121 OverdampedViscous method
  hoomd/md/TwoStepBD.cc
  hoomd/md/TwoStepBD.h
  hoomd/md/TwoStepBDGPU.cc
  hoomd/md/TwoStepBDGPU.cu
  hoomd/md/TwoStepBDGPU.h
  hoomd/md/TwoStepRATTLEBD.h
  hoomd/md/TwoStepRATTLEBDGPU.cuh
  hoomd/md/TwoStepRATTLEBDGPU.h
  hoomd/md/methods/__init__.py
  hoomd/md/methods/methods.py
  hoomd/md/methods/rattle.py
  hoomd/md/pytest/test_methods.py
  sphinx-doc/module-md-methods-rattle.rst
  sphinx-doc/module-md-methods.rst
Labels: validate

#1124 Fix rigid body bugs
  hoomd/ParticleData.cc
  hoomd/md/ForceComposite.cc
  hoomd/md/constrain.py
  hoomd/md/integrate.py
  hoomd/md/pytest/test_rigid.py
Labels: validate

#1098 Implement custom mutability error for initialized simulations
  hoomd/error.py
  hoomd/md/manifold.py
  hoomd/operation.py
  hoomd/pytest/test_box_resize.py
  hoomd/pytest/test_dcd.py
  hoomd/pytest/test_simulation.py
  sphinx-doc/module-hoomd-error.rst
Labels: validate

#1129 Fix hoomd.Operations.__len__
  hoomd/operations.py
  hoomd/pytest/CMakeLists.txt
  hoomd/pytest/test_operations.py
Labels: validate

#1134 Support llvm12
  .github/workflows/release.yml
  .github/workflows/templates/configurations.yml
  .github/workflows/templates/workflow.yml
  .github/workflows/test.yml
  BUILDING.rst
  CMake/hoomd/FindCUDALibs.cmake
  hoomd/hpmc/CMakeLists.txt
  hoomd/hpmc/EvalFactory.cc
  hoomd/hpmc/ExternalFieldEvalFactory.cc
  hoomd/hpmc/GPUEvalFactory.h
  hoomd/hpmc/KaleidoscopeJIT.h
  hoomd/hpmc/PatchEnergyJITGPU.cc
  hoomd/hpmc/PatchEnergyJITUnionGPU.cc
  hoomd/hpmc/pair/user.py
Labels: release

#1133 Improve Error Messaging
  hoomd/data/parameterdicts.py
  hoomd/data/typeconverter.py
  hoomd/error.py
  hoomd/operation.py
  hoomd/pytest/test_type_parameter_dict.py
Labels: validate

#1132 Fix RATTLE methods on the GPU
  hoomd/GPUPartition.cuh
  hoomd/md/TwoStepRATTLELangevinGPU.h
  hoomd/md/TwoStepRATTLENVEGPU.h
  hoomd/mpcd/CellThermoComputeGPU.cc
  hoomd/mpcd/SorterGPU.cc
Labels: validate

#1140 Jit llvm one library
  hoomd/hpmc/CMakeLists.txt
  hoomd/hpmc/EvalFactory.cc
  hoomd/hpmc/KaleidoscopeJIT.h
Labels: validate, release

#1137 Add note about pandoc
  BUILDING.rst
Labels: validate

#1073 Fire v3
  .pre-commit-config.yaml
  hoomd/CMakeLists.txt
  hoomd/GPUArray.h
  hoomd/GPUVector.h
  hoomd/md/CMakeLists.txt
  hoomd/md/FIREEnergyMinimizer.cc
  hoomd/md/FIREEnergyMinimizer.h
  hoomd/md/FIREEnergyMinimizerGPU.cc
  hoomd/md/FIREEnergyMinimizerGPU.cu
  hoomd/md/FIREEnergyMinimizerGPU.h
  hoomd/md/__init__.py
  hoomd/md/minimize/CMakeLists.txt
  hoomd/md/minimize/__init__.py
  hoomd/md/minimize/fire.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_minimize_fire.py
  hoomd/minimize/fire.py
  hoomd/test/test_gpu_array.cc
  setup.cfg
  sphinx-doc/module-md-minimize.rst
  sphinx-doc/package-md.rst
Labels: validate

#1141 Revise units documentation
  sphinx-doc/units.rst
Labels: validate

#1143 Evaluator pair dlvo bug fix
  hoomd/md/CMakeLists.txt
  sphinx-doc/credits.rst
Labels: validate

#1145 Fix setting of ptr for zero sized ManagedArrays.
  hoomd/ManagedArray.h
Labels: validate

#1144 Rename pivot_move_ratio in the Cluster updater
  hoomd/hpmc/UpdaterClusters.h
  hoomd/hpmc/pytest/test_clusters.py
  hoomd/hpmc/update.py
Labels: validate

#1148 Use non-static variables to define max block sizes
  hoomd/CellListGPU.cu
  hoomd/LoadBalancerGPU.cu
  hoomd/hpmc/ComputeFreeVolumeGPU.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPU.cu
  hoomd/hpmc/IntegratorHPMCMonoGPU.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletants.cu
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletants.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsAuxilliaryPhase1.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsAuxilliaryPhase2.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUMoves.cuh
  hoomd/hpmc/UpdaterClustersGPU.cu
  hoomd/hpmc/UpdaterClustersGPU.cuh
  hoomd/hpmc/UpdaterClustersGPUDepletants.cuh
  hoomd/md/AnisoPotentialPairGPU.cuh
  hoomd/md/BondTablePotentialGPU.cu
  hoomd/md/CosineSqAngleForceGPU.cu
  hoomd/md/ForceCompositeGPU.cu
  hoomd/md/ForceDistanceConstraintGPU.cu
  hoomd/md/HarmonicAngleForceGPU.cu
  hoomd/md/HarmonicDihedralForceGPU.cu
  hoomd/md/HarmonicImproperForceGPU.cu
  hoomd/md/NeighborListGPU.cu
  hoomd/md/NeighborListGPUBinned.cu
  hoomd/md/NeighborListGPUStencil.cu
  hoomd/md/NeighborListGPUTree.cu
  hoomd/md/OPLSDihedralForceGPU.cu
  hoomd/md/PPPMForceComputeGPU.cu
  hoomd/md/PotentialBondGPU.cuh
  hoomd/md/PotentialExternalGPU.cuh
  hoomd/md/PotentialPairDPDThermoGPU.cuh
  hoomd/md/PotentialPairGPU.cuh
  hoomd/md/PotentialTersoffGPU.cuh
  hoomd/md/TableAngleForceGPU.cu
  hoomd/md/TableDihedralForceGPU.cu
  hoomd/md/TwoStepNPTMTKGPU.cu
  hoomd/md/TwoStepNVEGPU.cu
  hoomd/md/TwoStepNVTMTKGPU.cu
  hoomd/md/TwoStepRATTLENVEGPU.cu
  hoomd/md/TwoStepRATTLENVEGPU.cuh
  hoomd/metal/EAMForceGPU.cu
  hoomd/mpcd/ATCollisionMethodGPU.cu
  hoomd/mpcd/BounceBackNVEGPU.cu
  hoomd/mpcd/BounceBackNVEGPU.cuh
  hoomd/mpcd/CellCommunicator.cuh
  hoomd/mpcd/CellListGPU.cu
  hoomd/mpcd/CellThermoComputeGPU.cu
  hoomd/mpcd/CommunicatorGPU.cu
  hoomd/mpcd/ConfinedStreamingMethodGPU.cuh
  hoomd/mpcd/ParticleData.cu
  hoomd/mpcd/SRDCollisionMethodGPU.cu
  hoomd/mpcd/SlitGeometryFillerGPU.cu
  hoomd/mpcd/SlitPoreGeometryFillerGPU.cu
  hoomd/mpcd/SorterGPU.cu
Labels: validate

#1146 Fix pair.Table on the GPU
  hoomd/md/EvaluatorPairTable.h
  hoomd/md/PotentialPairGPU.cuh
  hoomd/md/pair/pair.py
Labels: validate
