Repository glotzerlab/hoomd-blue, pull requests merged in 2021-05, with the labels that each got.

#842 RATTLE integrators and manifold class
  hoomd/md/CMakeLists.txt
  hoomd/md/IntegrationMethodTwoStep.h
  hoomd/md/IntegratorTwoStep.cc
  hoomd/md/ManifoldDiamond.cc
  hoomd/md/ManifoldDiamond.h
  hoomd/md/ManifoldEllipsoid.cc
  hoomd/md/ManifoldEllipsoid.h
  hoomd/md/ManifoldGyroid.cc
  hoomd/md/ManifoldGyroid.h
  hoomd/md/ManifoldPrimitive.cc
  hoomd/md/ManifoldPrimitive.h
  hoomd/md/ManifoldSphere.cc
  hoomd/md/ManifoldSphere.h
  hoomd/md/ManifoldXYPlane.cc
  hoomd/md/ManifoldXYPlane.h
  hoomd/md/ManifoldZCylinder.cc
  hoomd/md/ManifoldZCylinder.h
  hoomd/md/TwoStepLangevinGPU.cu
  hoomd/md/TwoStepRATTLEBD.h
  hoomd/md/TwoStepRATTLEBDGPU.cuh
  hoomd/md/TwoStepRATTLEBDGPU.h
  hoomd/md/TwoStepRATTLELangevin.h
  hoomd/md/TwoStepRATTLELangevinGPU.cu
  hoomd/md/TwoStepRATTLELangevinGPU.cuh
  hoomd/md/TwoStepRATTLELangevinGPU.h
  hoomd/md/TwoStepRATTLENVE.h
  hoomd/md/TwoStepRATTLENVEGPU.cu
  hoomd/md/TwoStepRATTLENVEGPU.cuh
  hoomd/md/TwoStepRATTLENVEGPU.h
  hoomd/md/__init__.py
  hoomd/md/all_kernels_diamond_manifold.cu
  hoomd/md/all_kernels_ellipsoid_manifold.cu
  hoomd/md/all_kernels_gyroid_manifold.cu
  hoomd/md/all_kernels_primitive_manifold.cu
  hoomd/md/all_kernels_sphere_manifold.cu
  hoomd/md/all_kernels_xyplane_manifold.cu
  hoomd/md/all_kernels_zcylinder_manifold.cu
  hoomd/md/integrate.py
  hoomd/md/manifold.py
  hoomd/md/methods.py
  hoomd/md/module-md.cc
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_manifolds.py
  hoomd/md/pytest/test_methods.py
  hoomd/md/pytest/test_write_debug_data_md.py
  hoomd/operation.py
  sphinx-doc/module-md-manifold.rst
  sphinx-doc/module-md-methods.rst
  sphinx-doc/package-md.rst
Labels: API 3.0, md

#991 Use GitHub Actions for CI
  .azp/environment.yml
  .azp/release.yml
  .azp/templates/build.yml
  .azp/templates/run_tests.yml
  .azp/templates/run_validation_tests.yml
  .azp/test.yml
  .azp/validate.yml
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/make-changelog-md.sh
  .github/workflows/make_workflows.py
  .github/workflows/release.yml
  .github/workflows/templates/configurations.yml
  .github/workflows/templates/release.yml
  .github/workflows/templates/test.yml
  .github/workflows/templates/workflow.yml
  .github/workflows/test.yml
  ARCHITECTURE.md
  CMakeLists.txt
  README.md
  hoomd/CMakeLists.txt
  hoomd/conftest.py
  hoomd/pytest/CMakeLists.txt
  hoomd/pytest_plugin_validate.py
  sphinx-doc/index.rst
Labels: release, validate

#928 convert compute.thermo_hma to v3 API
  hoomd/md/ComputeThermoHMA.cc
  hoomd/md/ComputeThermoHMA.h
  hoomd/md/compute.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_thermoHMA.py
  sphinx-doc/module-md-compute.rst
Labels: validate

#994 Release 3.0.0 beta.6
  .bumpversion.cfg
  CHANGELOG.rst
  CMakeLists.txt
  INSTALLING.rst
  sphinx-doc/conf.py
Labels: release, validate

#1000 Replace docs reference to undocumented hoomd.md.integrate module with hoomd.md.Integrator.
  hoomd/operations.py
Labels: documentation, validate

#1007 Remove rescale temp
  hoomd/md/CMakeLists.txt
  hoomd/md/Enforce2DUpdater.cc
  hoomd/md/Enforce2DUpdater.h
  hoomd/md/Enforce2DUpdaterGPU.cc
  hoomd/md/Enforce2DUpdaterGPU.cu
  hoomd/md/Enforce2DUpdaterGPU.cuh
  hoomd/md/Enforce2DUpdaterGPU.h
  hoomd/md/TempRescaleUpdater.cc
  hoomd/md/TempRescaleUpdater.h
  hoomd/md/module-md.cc
  hoomd/md/test/CMakeLists.txt
  hoomd/md/test/test_enforce2d_updater.cc
  hoomd/md/test/test_temp_rescale_updater.cc
  hoomd/md/update.py
Labels: validate

#1022 Import optional modules based on build configuration
  hoomd/CMakeLists.txt
  hoomd/__init__.py
  hoomd/version.py
  hoomd/version_config.py.in
Labels: validate

#996 Add MD LJ validation tests
  hoomd/conftest.py
  hoomd/md/ComputeThermo.cc
  hoomd/md/ComputeThermo.h
  hoomd/md/compute.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_lj_equation_of_state.py
Labels: validate
