Repository glotzerlab/hoomd-blue, pull requests merged in 2022-04, with the labels that each got.

#1287 Add Table Potential to CMakeList
  hoomd/md/CMakeLists.txt
  sphinx-doc/credits.rst
Labels: validate

#1284 Add Rigid filter to sphinx documentation
  hoomd/filter/rigid.py
  sphinx-doc/module-hoomd-filter.rst
Labels: validate

#1288 Fix Tag equality check behavior
  hoomd/filter/tags.py
  hoomd/pytest/test_filter.py
Labels: validate

#1290 Fix TPS updating
  hoomd/System.cc
  hoomd/pytest/test_simulation.py
  hoomd/simulation.py
Labels: validate

#1296 Release v3.0.1
  .bumpversion.cfg
  .mailmap
  CHANGELOG.rst
  CMakeLists.txt
  hoomd/hpmc/external/user.py
  hoomd/hpmc/pair/user.py
  hoomd/pytest/test_simulation.py
  sphinx-doc/conf.py
Labels: validate, release

#1292 ALJ Debug Assert Failure
  hoomd/md/pytest/aniso_forces_and_energies.json
Labels: validate

#1280 Fix/fugacity
  hoomd/hpmc/IntegratorHPMCMono.h
  hoomd/hpmc/IntegratorHPMCMonoGPU.h
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletants.cu
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletants.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsAuxilliaryPhase1.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsAuxilliaryPhase2.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsAuxilliaryTypes.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsTypes.cuh
  hoomd/hpmc/UpdaterClusters.h
  hoomd/hpmc/UpdaterClustersGPU.h
  hoomd/hpmc/UpdaterClustersGPUDepletants.cuh
  hoomd/hpmc/UpdaterMuVT.h
  hoomd/hpmc/XenoCollide3D.h
  hoomd/hpmc/XenoSweep3D.h
  hoomd/hpmc/integrate.py
  hoomd/hpmc/pytest/test_shape.py
  hoomd/hpmc/update.py
  hoomd/operation.py
Labels: validate

#1302 Support LLVM 13
  .github/workflows/templates/configurations.yml
  .github/workflows/test.yml
  hoomd/Communicator.cc
  hoomd/hpmc/KaleidoscopeJIT.h
  hoomd/metal/EAMForceCompute.cc
Labels: validate, release

#1303 Fix test_energy_shifting for Pair potentials
  hoomd/md/pytest/test_potential.py
Labels: validate

#1300 Zero forces in CustomForceCompute
  hoomd/md/CustomForceCompute.cc
  hoomd/md/pytest/test_custom_force.py
Labels: validate

#1067 Alchemical MD integration methods
  hoomd/ParticleGroup.cc
  hoomd/ParticleGroup.h
  hoomd/data/parameterdicts.py
  hoomd/md/AlchemostatTwoStep.h
  hoomd/md/AlchemyData.h
  hoomd/md/AllDriverPotentialPairGPU.cuh
  hoomd/md/AllPairPotentials.h
  hoomd/md/CMakeLists.txt
  hoomd/md/EvaluatorPairLJGauss.h
  hoomd/md/IntegrationMethodTwoStep.h
  hoomd/md/IntegratorTwoStep.cc
  hoomd/md/LJGaussDriverPotentialPairGPU.cu
  hoomd/md/PotentialPairAlchemical.h
  hoomd/md/PotentialPairAlchemicalNormalized.h
  hoomd/md/TwoStepNVTAlchemy.cc
  hoomd/md/TwoStepNVTAlchemy.h
  hoomd/md/__init__.py
  hoomd/md/alchemy/CMakeLists.txt
  hoomd/md/alchemy/__init__.py
  hoomd/md/alchemy/methods.py
  hoomd/md/alchemy/pair.py
  hoomd/md/many_body.py
  hoomd/md/module-md.cc
  hoomd/md/pair/__init__.py
  hoomd/md/pair/pair.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/forces_and_energies.json
  hoomd/md/pytest/test_alchemostat.py
  hoomd/md/pytest/test_potential.py
  hoomd/operation.py
  hoomd/pytest/test_type_parameter_dict.py
  sphinx-doc/citing.rst
  sphinx-doc/conf.py
  sphinx-doc/module-md-alchemy-methods.rst
  sphinx-doc/module-md-alchemy-pair.rst
  sphinx-doc/module-md-alchemy.rst
  sphinx-doc/module-md-pair.rst
  sphinx-doc/package-md.rst
Labels: validate, essential

#1301 Point download link to GitHub releases.
  .bumpversion.cfg
  BUILDING.rst
Labels: validate

#1306 A few documentation fixes
  hoomd/md/external/wall.py
  hoomd/md/pair/aniso.py
  hoomd/md/pair/pair.py
Labels: validate

#989 Enable HPMC Alchemy
  .mailmap
  hoomd/RNGIdentifiers.h
  hoomd/hpmc/CMakeLists.txt
  hoomd/hpmc/ShapeMoves.h
  hoomd/hpmc/ShapeUtils.cc
  hoomd/hpmc/ShapeUtils.h
  hoomd/hpmc/UpdaterShape.h
  hoomd/hpmc/__init__.py
  hoomd/hpmc/module.cc
  hoomd/hpmc/module_convex_polyhedron.cc
  hoomd/hpmc/module_convex_spheropolyhedron.cc
  hoomd/hpmc/module_ellipsoid.cc
  hoomd/hpmc/module_sphere.cc
  hoomd/hpmc/modules.h
  hoomd/hpmc/pytest/CMakeLists.txt
  hoomd/hpmc/pytest/test_shape_updater.py
  hoomd/hpmc/pytest/test_shape_utils.py
  hoomd/hpmc/shape_move.py
  hoomd/hpmc/update.py
  hoomd/md/pair/pair.py
  sphinx-doc/citing.rst
  sphinx-doc/module-hpmc-shape_move.rst
  sphinx-doc/module-hpmc-update.rst
  sphinx-doc/package-hpmc.rst
Labels: validate, essential

#1309 Release v3.1.0.
  .bumpversion.cfg
  .github/workflows/release.yml
  .github/workflows/templates/release.yml
  .github/workflows/templates/test.yml
  .github/workflows/test.yml
  BUILDING.rst
  CHANGELOG.rst
  CMakeLists.txt
  hoomd/hpmc/external/user.py
  hoomd/hpmc/pair/user.py
  sphinx-doc/conf.py
Labels: validate, release
