Repository glotzerlab/hoomd-blue, pull requests merged in 2022-09, with the labels that each got.

#1390 Allow more particle and bond types in simulations on the GPU.
  hoomd/BondedGroupData.cc
  hoomd/CommunicatorGPU.cu
  hoomd/ParticleData.cc
  hoomd/hpmc/ComputeFreeVolumeGPU.cuh
  hoomd/md/AnisoPotentialPairGPU.cuh
  hoomd/md/BondTablePotentialGPU.cc
  hoomd/md/BondTablePotentialGPU.cu
  hoomd/md/BondTablePotentialGPU.cuh
  hoomd/md/NeighborListGPU.cu
  hoomd/md/NeighborListGPUBinned.cc
  hoomd/md/NeighborListGPUBinned.cu
  hoomd/md/NeighborListGPUBinned.cuh
  hoomd/md/NeighborListGPUStencil.cc
  hoomd/md/NeighborListGPUStencil.cu
  hoomd/md/NeighborListGPUStencil.cuh
  hoomd/md/PotentialBondGPU.cuh
  hoomd/md/PotentialBondGPU.h
  hoomd/md/PotentialExternalGPU.cuh
  hoomd/md/PotentialExternalGPU.h
  hoomd/md/PotentialPairDPDThermoGPU.cuh
  hoomd/md/PotentialPairDPDThermoGPU.h
  hoomd/md/PotentialPairGPU.cuh
  hoomd/md/PotentialSpecialPairGPU.h
  hoomd/md/PotentialTersoffGPU.cuh
  hoomd/md/TwoStepBDGPU.cc
  hoomd/md/TwoStepBDGPU.cu
  hoomd/md/TwoStepLangevinGPU.cc
  hoomd/md/TwoStepLangevinGPU.cu
  hoomd/md/TwoStepLangevinGPU.cuh
  hoomd/md/TwoStepRATTLEBDGPU.cuh
  hoomd/md/TwoStepRATTLEBDGPU.h
  hoomd/md/TwoStepRATTLELangevinGPU.cu
  hoomd/md/TwoStepRATTLELangevinGPU.cuh
  hoomd/md/TwoStepRATTLELangevinGPU.h
Labels: validate

#1392 Test CUDA 11.7 with GitHub Actions, fix cupy tests with cuda 11.7, and add a Debug build to CI checks.
  .github/workflows/release.yml
  .github/workflows/templates/configurations.yml
  .github/workflows/templates/test.yml
  .github/workflows/templates/workflow.yml
  .github/workflows/test.yml
  hoomd/CommunicatorGPU.cu
  hoomd/md/PotentialTersoff.h
  hoomd/md/pytest/test_custom_force.py
  hoomd/pytest/test_local_snapshot.py
  hoomd/pytest/test_snapshot.py
Labels: validate, release

#1400 Remove fix_cudart_rpath.
  CMake/hoomd/hoomd-macros.cmake
  example_plugins/pair_plugin/CMakeLists.txt
  example_plugins/updater_plugin/CMakeLists.txt
  hoomd/CMakeLists.txt
  hoomd/hpmc/CMakeLists.txt
  hoomd/hpmc/test/CMakeLists.txt
  hoomd/md/CMakeLists.txt
  hoomd/md/test/CMakeLists.txt
  hoomd/metal/CMakeLists.txt
  hoomd/mpcd/CMakeLists.txt
  hoomd/mpcd/test/CMakeLists.txt
  hoomd/test/CMakeLists.txt
  sphinx-doc/migrating.rst
Labels: breaking, validate, release

#1402 Fix/ndarray validation
  hoomd/conftest.py
  hoomd/data/collections.py
  hoomd/pytest/test_collections.py
Labels: validate

#1403 Replace deprecated usage of cusparse.
  CMake/hoomd/HOOMDCUDASetup.cmake
  hoomd/md/ForceDistanceConstraintGPU.cc
  hoomd/md/ForceDistanceConstraintGPU.cu
  hoomd/md/ForceDistanceConstraintGPU.cuh
Labels: validate, release

#1407 Prepare to release v3.5.0.
  .bumpversion.cfg
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/templates/test.yml
  .github/workflows/test.yml
  BUILDING.rst
  CHANGELOG.rst
  CMakeLists.txt
  hoomd/hpmc/external/user.py
  hoomd/hpmc/pair/user.py
  sphinx-doc/conf.py
Labels: breaking, validate, release

#1408 Fix pair table performance.
  hoomd/md/AnisoPotentialPairGPU.cuh
  hoomd/md/EvaluatorPairTable.h
  hoomd/md/PotentialBondGPU.cuh
  hoomd/md/PotentialPair.h
  hoomd/md/PotentialPairAlchemical.h
  hoomd/md/PotentialPairDPDThermo.h
  hoomd/md/PotentialPairDPDThermoGPU.cuh
  hoomd/md/PotentialSpecialPair.h
  hoomd/md/PotentialTersoff.h
  hoomd/md/PotentialTersoffGPU.cuh
Labels: validate

#1410 Add default value for rounding_radii when using ALJ
  hoomd/md/pair/aniso.py
Labels: validate
