Repository glotzerlab/hoomd-blue, pull requests merged in 2022-08, with the labels that each got.

#1371 Add logo
  README.md
  sphinx-doc/_static/css/hoomd-theme.css
  sphinx-doc/_templates/footer.html
  sphinx-doc/conf.py
  sphinx-doc/hoomdblue-logo-favicon.svg
  sphinx-doc/hoomdblue-logo-horizontal.svg
  sphinx-doc/hoomdblue-logo-vertical.svg
  sphinx-doc/index.rst
  sphinx-doc/logo.rst
Labels: validate

#1346 Initial changes to compile on AMD
  BUILDING.rst
  CMake/HIP/FindHIP.cmake
  CMake/HIP/FindHIP/run_hipcc.cmake
  CMake/HIP/FindHIP/run_make2cmake.cmake
  CMake/hoomd/FindCUDALibs.cmake
  CMake/hoomd/HOOMDHIPSetup.cmake
  CMake/hoomd/hipcc.cmake
  CMakeLists.txt
  hoomd/CMakeLists.txt
  hoomd/SnapshotSystemData.cc
  hoomd/md/BondTablePotential.cc
  hoomd/md/CMakeLists.txt
  hoomd/md/EvaluatorTersoff.h
  hoomd/md/ForceComposite.h
  hoomd/md/OPLSDihedralForceCompute.cc
  hoomd/md/TwoStepRATTLEBDGPU.h
  hoomd/md/TwoStepRATTLENVEGPU.cu
  hoomd/md/TwoStepRATTLENVEGPU.cuh
Labels: validate

#1373 Document installation procedure to enable run time compilation on macos.
  INSTALLING.rst
  sphinx-doc/features.rst
Labels: validate

#1363 Feat/movement limited method
  hoomd/md/TwoStepNVE.cc
  hoomd/md/TwoStepNVE.h
  hoomd/md/TwoStepNVEGPU.cc
  hoomd/md/TwoStepNVEGPU.h
  hoomd/md/TwoStepRATTLENVE.h
  hoomd/md/TwoStepRATTLENVEGPU.h
  hoomd/md/methods/__init__.py
  hoomd/md/methods/methods.py
  hoomd/md/methods/rattle.py
  hoomd/md/pytest/test_methods.py
  sphinx-doc/module-md-methods-rattle.rst
  sphinx-doc/module-md-methods.rst
Labels: validate

#1376 Add needed thrust includes.
  hoomd/BondedGroupData.cu
  hoomd/CommunicatorGPU.cu
  hoomd/MeshGroupData.cu
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletants.cu
  hoomd/hpmc/UpdaterClustersGPU.cu
  hoomd/md/ForceCompositeGPU.cu
  hoomd/md/MolecularForceCompute.cu
  hoomd/mpcd/CommunicatorGPU.cu
Labels: validate

#1372 Export HalfStepHook
  hoomd/HalfStepHook.h
  hoomd/md/CMakeLists.txt
  hoomd/md/HalfStepHook.cc
  hoomd/md/IntegratorTwoStep.cc
  hoomd/md/__init__.py
  hoomd/md/half_step_hook.py
  hoomd/md/integrate.py
  hoomd/md/module-md.cc
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_half_step_hook.py
  sphinx-doc/credits.rst
  sphinx-doc/package-md.rst
Labels: validate

#1379 Prepare to release v3.4.0.
  .bumpversion.cfg
  .github/workflows/stale.yml
  BUILDING.rst
  CHANGELOG.rst
  CMakeLists.txt
  hoomd/Integrator.cc
  hoomd/Integrator.h
  hoomd/hpmc/IntegratorHPMCMonoGPU.h
  hoomd/hpmc/external/user.py
  hoomd/hpmc/pair/user.py
  hoomd/md/IntegratorTwoStep.cc
  sphinx-doc/conf.py
Labels: validate, release

#1378 Update gpu memory management.
  hoomd/Autotuner.h
  hoomd/CMakeLists.txt
  hoomd/CachedAllocator.h
  hoomd/ExecutionConfiguration.cc
  hoomd/ExecutionConfiguration.h
  hoomd/GPUArray.h
  hoomd/GPUFlags.h
  hoomd/GPUPolymorph.h
  hoomd/GlobalArray.h
  hoomd/MemoryTraceback.cc
  hoomd/MemoryTraceback.h
  hoomd/device.py
  hoomd/managed_allocator.h
  sphinx-doc/deprecated.rst
Labels: validate

#1377 Raise an error when there are duplicate types.
  hoomd/BondedGroupData.cc
  hoomd/BondedGroupData.h
  hoomd/MeshGroupData.cc
  hoomd/ParticleData.cc
  hoomd/ParticleData.h
  hoomd/pytest/test_snapshot.py
Labels: validate

#1384 Issue forms
  .bumpversion.cfg
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/support.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/task.yml
Labels: validate

#1356 Implement brute force overlap search for SDF compute
  hoomd/hpmc/ComputeSDF.h
  hoomd/hpmc/IntegratorHPMC.h
  hoomd/hpmc/IntegratorHPMCMono.h
  hoomd/hpmc/compute.py
  hoomd/hpmc/pytest/test_compute_sdf.py
Labels: validate, essential

#1387 Document NeighborList properties in sphinx
  sphinx-doc/module-md-nlist.rst
Labels: validate

#1388 Add missing Autotuned.h to _hoomd_headers
  hoomd/CMakeLists.txt
Labels: validate

#1382 Refactor updater plugin example to work with version 3, add example MD potential pair
  CMakeLists.txt
  example_plugin/example_plugin/update.py
  example_plugins/CMakeLists.txt
  example_plugins/pair_plugin/CMakeLists.txt
  example_plugins/pair_plugin/EvaluatorPairExample.h
  example_plugins/pair_plugin/PotentialPairExampleGPUKernel.cu
  example_plugins/pair_plugin/__init__.py
  example_plugins/pair_plugin/module.cc
  example_plugins/pair_plugin/pair.py
  example_plugins/pair_plugin/pytest/CMakeLists.txt
  example_plugins/pair_plugin/pytest/__init__.py
  example_plugins/pair_plugin/pytest/test_example_pair.py
  example_plugins/updater_plugin/CMakeLists.txt
  example_plugins/updater_plugin/ExampleUpdater.cc
  example_plugins/updater_plugin/ExampleUpdater.cu
  example_plugins/updater_plugin/ExampleUpdater.cuh
  example_plugins/updater_plugin/ExampleUpdater.h
  example_plugins/updater_plugin/__init__.py
  example_plugins/updater_plugin/module.cc
  example_plugins/updater_plugin/pytest/CMakeLists.txt
  example_plugins/updater_plugin/pytest/__init__.py
  example_plugins/updater_plugin/pytest/test_example_updater.py
  example_plugins/updater_plugin/update.py
  hoomd/CMakeLists.txt
  hoomd/example_plugin
  hoomd/example_plugins
  hoomd/md/pair/pair.py
  hoomd/pytest.ini
  sphinx-doc/components.rst
  sphinx-doc/credits.rst
Labels: validate
