Repository glotzerlab/hoomd-blue, pull requests merged in 2022-02, with the labels that each got.

#1214 Enable variant spring constants for HPMC harmonic fields
  hoomd/hpmc/ExternalCallback.h
  hoomd/hpmc/ExternalField.h
  hoomd/hpmc/ExternalFieldComposite.h
  hoomd/hpmc/ExternalFieldHarmonic.h
  hoomd/hpmc/ExternalFieldJIT.h
  hoomd/hpmc/ExternalFieldWall.h
  hoomd/hpmc/IntegratorHPMCMono.h
  hoomd/hpmc/UpdaterBoxMC.cc
  hoomd/hpmc/external/field.py
  hoomd/hpmc/pytest/test_external.py
Labels: enhancement, validate

#1217 Fix special pair forces
  hoomd.code-workspace
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_special_pair.py
  hoomd/md/special_pair.py
Labels: validate

#1218 Add linear_momentum loggable.
  hoomd/Integrator.cc
  hoomd/Integrator.h
  hoomd/md/integrate.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_integrate.py
Labels: validate

#1221 Add the bond, angle, and dihedral table potentials to the v3 API.
  hoomd/md/BondTablePotential.cc
  hoomd/md/BondTablePotential.h
  hoomd/md/TableAngleForceCompute.cc
  hoomd/md/TableAngleForceCompute.h
  hoomd/md/TableDihedralForceCompute.cc
  hoomd/md/TableDihedralForceCompute.h
  hoomd/md/angle.py
  hoomd/md/bond.py
  hoomd/md/dihedral.py
  hoomd/md/pair/pair.py
  hoomd/md/pytest/test_angle.py
  hoomd/md/pytest/test_bond.py
  hoomd/md/pytest/test_dihedral.py
  hoomd/md/pytest/test_special_pair.py
  sphinx-doc/migrating.rst
  sphinx-doc/module-md-angle.rst
  sphinx-doc/module-md-bond.rst
  sphinx-doc/module-md-dihedral.rst
Labels: validate

#1220 Port improper harmonic to v3
  .pre-commit-config.yaml
  hoomd/md/HarmonicImproperForceCompute.cc
  hoomd/md/HarmonicImproperForceCompute.h
  hoomd/md/improper.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/test_improper.py
  setup.cfg
  sphinx-doc/migrating.rst
  sphinx-doc/module-md-improper.rst
Labels: validate

#992 Implements an anisotropic Lennard-Jones-like potential
  BUILDING.rst
  hoomd/Integrator.cc
  hoomd/VectorMath.h
  hoomd/conftest.py
  hoomd/data/typeparam.py
  hoomd/md/AllAnisoPairPotentials.h
  hoomd/md/AllDriverAnisoPotentialPairGPU.cu
  hoomd/md/AllDriverAnisoPotentialPairGPU.cuh
  hoomd/md/AnisoPotentialPair.h
  hoomd/md/AnisoPotentialPairGPU.cuh
  hoomd/md/AnisoPotentialPairGPU.h
  hoomd/md/CMakeLists.txt
  hoomd/md/EvaluatorPairALJ.h
  hoomd/md/EvaluatorPairDipole.h
  hoomd/md/EvaluatorPairGB.h
  hoomd/md/GJK_SV.h
  hoomd/md/PotentialPairGPU.cuh
  hoomd/md/module-md.cc
  hoomd/md/pair/aniso.py
  hoomd/md/pytest/CMakeLists.txt
  hoomd/md/pytest/aniso_forces_and_energies.json
  hoomd/md/pytest/test_alj.py
  hoomd/md/pytest/test_aniso_pair.py
  sphinx-doc/module-md-pair-aniso.rst
Labels: validate, release

#1230 Document C++ code and the build system.
  ARCHITECTURE.md
Labels: validate

#1234 Remove DEM
  CMakeLists.txt
  hoomd/CMakeLists.txt
  hoomd/__init__.py
  hoomd/dem/CMakeLists.txt
  hoomd/dem/DEM2DForceCompute.cc
  hoomd/dem/DEM2DForceCompute.h
  hoomd/dem/DEM2DForceComputeGPU.cc
  hoomd/dem/DEM2DForceComputeGPU.h
  hoomd/dem/DEM2DForceGPU.cu
  hoomd/dem/DEM2DForceGPU.cuh
  hoomd/dem/DEM3DForceCompute.cc
  hoomd/dem/DEM3DForceCompute.h
  hoomd/dem/DEM3DForceComputeGPU.cc
  hoomd/dem/DEM3DForceComputeGPU.h
  hoomd/dem/DEM3DForceGPU.cu
  hoomd/dem/DEM3DForceGPU.cuh
  hoomd/dem/DEMEvaluator.cc
  hoomd/dem/DEMEvaluator.h
  hoomd/dem/NoFriction.h
  hoomd/dem/SWCAPotential.cc
  hoomd/dem/SWCAPotential.h
  hoomd/dem/VectorMath.h
  hoomd/dem/WCAPotential.cc
  hoomd/dem/WCAPotential.h
  hoomd/dem/__init__.py
  hoomd/dem/atomics.cuh
  hoomd/dem/module.cc
  hoomd/dem/pair.py
  hoomd/dem/params.py
  hoomd/dem/templateInstances/DEM2DForce_NF_SWCA.cc
  hoomd/dem/templateInstances/DEM2DForce_NF_SWCA.cu
  hoomd/dem/templateInstances/DEM2DForce_NF_WCA.cc
  hoomd/dem/templateInstances/DEM2DForce_NF_WCA.cu
  hoomd/dem/templateInstances/DEM3DForce_NF_SWCA.cc
  hoomd/dem/templateInstances/DEM3DForce_NF_SWCA.cu
  hoomd/dem/templateInstances/DEM3DForce_NF_WCA.cc
  hoomd/dem/templateInstances/DEM3DForce_NF_WCA.cu
  hoomd/dem/utils.py
  hoomd/version.py
  hoomd/version_config.py.in
  sphinx-doc/conf.py
Labels: validate

#1235 ALJ Ellipsoids Bugfix
  hoomd/md/EvaluatorPairALJ.h
  hoomd/md/pytest/test_aniso_pair.py
Labels: validate

#1242 Release v3.0.0 beta.14
  .bumpversion.cfg
  CHANGELOG.rst
  CMakeLists.txt
  hoomd/hpmc/external/user.py
  hoomd/hpmc/pair/user.py
  sphinx-doc/conf.py
Labels: validate, release

#1249 Fix __iadd__ for list type
  hoomd/data/collections.py
  hoomd/pytest/test_collections.py
Labels: validate

#1246 Check if rcut is zero before computing tail correction
  hoomd/md/EvaluatorPairLJ.h
Labels: validate

#1255 Remove HPMCIntegrator.test_overlap
  hoomd/hpmc/IntegratorHPMCMono.h
  hoomd/hpmc/integrate.py
Labels: validate

#1256 Add missing thrust include.
  hoomd/md/MolecularForceCompute.cu
Labels: validate

#1244 Update ALJ Tests
  hoomd/md/pytest/test_alj.py
  hoomd/md/pytest/test_aniso_pair.py
Labels: validate

#1243 Document theory in hpmc
  hoomd.code-workspace
  hoomd/box.py
  hoomd/hpmc/ComputeFreeVolume.h
  hoomd/hpmc/__init__.py
  hoomd/hpmc/compute.py
  hoomd/hpmc/external/__init__.py
  hoomd/hpmc/external/field.py
  hoomd/hpmc/external/user.py
  hoomd/hpmc/external/wall.py
  hoomd/hpmc/integrate.py
  hoomd/hpmc/pair/__init__.py
  hoomd/hpmc/pair/user.py
  hoomd/hpmc/update.py
  hoomd/md/external/wall.py
  hoomd/update/remove_drift.py
  hoomd/variant.py
  sphinx-doc/citing.rst
  sphinx-doc/conf.py
  sphinx-doc/convex-polygon.svg
  sphinx-doc/convex-polyhedron.svg
  sphinx-doc/convex-spheropolygon.svg
  sphinx-doc/figures/box.ipynb
  sphinx-doc/figures/hpmc.ipynb
  sphinx-doc/figures/variant.ipynb
  sphinx-doc/module-hpmc-compute.rst
  sphinx-doc/module-hpmc-external-field.rst
  sphinx-doc/module-hpmc-external-user.rst
  sphinx-doc/module-hpmc-external-wall.rst
  sphinx-doc/module-hpmc-external.rst
  sphinx-doc/module-hpmc-integrate.rst
  sphinx-doc/module-hpmc-pair-user.rst
  sphinx-doc/module-hpmc-pair.rst
  sphinx-doc/module-hpmc-tune.rst
  sphinx-doc/module-hpmc-update.rst
  sphinx-doc/notation.rst
  sphinx-doc/simple-polygon.svg
Labels: validate

#1260 Remove get_ordered_vertices
  BUILDING.rst
  hoomd/md/pair/aniso.py
Labels: validate

#1258 Remove IntegratorData class and usage
  hoomd/CMakeLists.txt
  hoomd/IntegratorData.cc
  hoomd/IntegratorData.h
  hoomd/ParticleData.h
  hoomd/SnapshotSystemData.h
  hoomd/SystemDefinition.cc
  hoomd/SystemDefinition.h
  hoomd/md/IntegrationMethodTwoStep.cc
  hoomd/md/IntegrationMethodTwoStep.h
  hoomd/md/IntegratorTwoStep.cc
  hoomd/md/IntegratorTwoStep.h
  hoomd/md/TwoStepNPTMTK.cc
  hoomd/md/TwoStepNPTMTK.h
  hoomd/md/TwoStepNPTMTKGPU.cc
  hoomd/md/TwoStepNVE.cc
  hoomd/md/TwoStepNVE.h
  hoomd/md/TwoStepNVTMTK.cc
  hoomd/md/TwoStepNVTMTK.h
  hoomd/md/TwoStepNVTMTKGPU.cc
  hoomd/md/TwoStepRATTLENVE.h
  hoomd/md/TwoStepRATTLENVEGPU.h
  hoomd/md/methods/methods.py
  hoomd/md/methods/rattle.py
Labels: validate
