Repository glotzerlab/hoomd-blue, pull requests merged in 2023-09, with the labels that each got.

#1616 Add "How to determine the most efficient device."
  setup.cfg
  sphinx-doc/figures/determine-the-most-efficient-device.ipynb
  sphinx-doc/how-to.rst
  sphinx-doc/howto/custom-md-potential.rst
  sphinx-doc/howto/determine-the-most-efficient-device.py
  sphinx-doc/howto/determine-the-most-efficient-device.rst
  sphinx-doc/howto/spheres.gsd
  sphinx-doc/howto/wca-efficiency-131072.svg
  sphinx-doc/howto/wca-efficiency-2048.svg
Labels: validate

#1608 Add param_array to CPPExternalPotential
  hoomd/conftest.py
  hoomd/hpmc/ExternalFieldEvalFactory.cc
  hoomd/hpmc/ExternalFieldEvalFactory.h
  hoomd/hpmc/ExternalFieldJIT.h
  hoomd/hpmc/external/user.py
  hoomd/hpmc/pytest/test_external_user.py
Labels: enhancement, validate

#1613 Add "How to compute the free energy of solids."
  sphinx-doc/how-to.rst
  sphinx-doc/howto/compute-the-free-energy-of-solids.rst
Labels: validate

#1617 fix: table rendering of small numbers.
  hoomd/pytest/test_table.py
  hoomd/write/table.py
Labels: validate

#1621 Fix/hdf5 scalar detection
  hoomd/md/pytest/test_hdf5.py
  hoomd/write/hdf5.py
Labels: validate

#1624 Fix grammar on credits page
  sphinx-doc/credits.rst
Labels: validate

#1629 Call hipInit before MPI_Init.
  hoomd/module.cc
Labels: validate

#1626 Fix compile errors with Apple clang 15.
  hoomd/CommunicatorGPU.cc
  hoomd/ParticleData.cc
Labels: validate, release
