Repository glotzerlab/hoomd-blue, pull requests merged in 2024-01, with the labels that each got.

#1662 Periodic improper support
  hoomd/md/CMakeLists.txt
  hoomd/md/PeriodicImproper.h
  hoomd/md/PeriodicImproperForceCompute.cc
  hoomd/md/PeriodicImproperForceCompute.h
  hoomd/md/PeriodicImproperForceComputeGPU.cc
  hoomd/md/PeriodicImproperForceComputeGPU.h
  hoomd/md/PeriodicImproperForceGPU.cu
  hoomd/md/PeriodicImproperForceGPU.cuh
  hoomd/md/improper.py
  hoomd/md/module-md.cc
  hoomd/md/pytest/test_improper.py
  sphinx-doc/credits.rst
  sphinx-doc/module-md-improper.rst
Labels: validate

#1692 add warning message for the deprecated methods
  hoomd/tune/custom_tuner.py
  hoomd/update/custom_updater.py
  hoomd/write/custom_writer.py
  hoomd/write/hdf5.py
  sphinx-doc/deprecated.rst
Labels: validate

#1678 Add QuickCompress.allow_unsafe_resize
  hoomd/hpmc/UpdaterQuickCompress.cc
  hoomd/hpmc/UpdaterQuickCompress.h
  hoomd/hpmc/pytest/test_quick_compress.py
  hoomd/hpmc/update.py
Labels: validate

#1681 Reimplement MPCD particle sorter
  hoomd/mpcd/CMakeLists.txt
  hoomd/mpcd/Integrator.cc
  hoomd/mpcd/Sorter.cc
  hoomd/mpcd/Sorter.h
  hoomd/mpcd/SorterGPU.cc
  hoomd/mpcd/SorterGPU.h
  hoomd/mpcd/__init__.py
  hoomd/mpcd/integrate.py
  hoomd/mpcd/pytest/CMakeLists.txt
  hoomd/mpcd/pytest/test_integrator.py
  hoomd/mpcd/pytest/test_tune.py
  hoomd/mpcd/test/sorter_test.cc
  hoomd/mpcd/tune.py
  hoomd/mpcd/update.py
  sphinx-doc/module-mpcd-tune.rst
  sphinx-doc/package-mpcd.rst
Labels: validate

#1694 import GPUNotAvailableError to error.py
  hoomd/data/array.py
  hoomd/data/local_access_gpu.py
  hoomd/error.py
  hoomd/md/data/local_access_gpu.py
  hoomd/util.py
  sphinx-doc/deprecated.rst
  sphinx-doc/module-hoomd-error.rst
  sphinx-doc/module-hoomd-util.rst
Labels: validate

#1699 Remove custom action methods
  hoomd/custom/custom_operation.py
  hoomd/md/pytest/test_hdf5.py
  hoomd/tune/custom_tuner.py
  hoomd/update/custom_updater.py
  hoomd/write/custom_writer.py
  hoomd/write/hdf5.py
  sphinx-doc/migrating.rst
Labels: validate

#1676 Implement new HPMC pair potential framework
  hoomd/AABBTree.h
  hoomd/hpmc/CMakeLists.txt
  hoomd/hpmc/ComputeSDF.h
  hoomd/hpmc/IntegratorHPMC.cc
  hoomd/hpmc/IntegratorHPMC.h
  hoomd/hpmc/IntegratorHPMCMono.h
  hoomd/hpmc/PairPotential.cc
  hoomd/hpmc/PairPotential.h
  hoomd/hpmc/PairPotentialLennardJones.cc
  hoomd/hpmc/PairPotentialLennardJones.h
  hoomd/hpmc/PatchEnergyJIT.cc
  hoomd/hpmc/UpdaterBoxMC.cc
  hoomd/hpmc/UpdaterClusters.h
  hoomd/hpmc/UpdaterMuVT.h
  hoomd/hpmc/integrate.py
  hoomd/hpmc/module.cc
  hoomd/hpmc/pair/CMakeLists.txt
  hoomd/hpmc/pair/__init__.py
  hoomd/hpmc/pair/lennard_jones.py
  hoomd/hpmc/pair/pair.py
  hoomd/hpmc/pair/user.py
  hoomd/hpmc/pytest/CMakeLists.txt
  hoomd/hpmc/pytest/test_pair_lennard_jones.py
  sphinx-doc/deprecated.rst
  sphinx-doc/module-hpmc-pair.rst
Labels: enhancement, validate

#1696 Fix shapespace retreat
  hoomd/hpmc/ShapeMoves.h
  hoomd/hpmc/UpdaterShape.h
  hoomd/hpmc/pytest/test_shape_updater.py
Labels: validate

#1689 Refactor MPCD geometries
  hoomd/RNGIdentifiers.h
  hoomd/mpcd/BounceBackNVEGPU.cu
  hoomd/mpcd/BounceBackStreamingMethod.h
  hoomd/mpcd/BounceBackStreamingMethodGPU.cu
  hoomd/mpcd/BounceBackStreamingMethodGPU.cuh
  hoomd/mpcd/BounceBackStreamingMethodGPU.h
  hoomd/mpcd/BoundaryCondition.h
  hoomd/mpcd/BulkGeometry.h
  hoomd/mpcd/BulkStreamingMethod.cc
  hoomd/mpcd/BulkStreamingMethod.h
  hoomd/mpcd/BulkStreamingMethodGPU.cc
  hoomd/mpcd/BulkStreamingMethodGPU.cu
  hoomd/mpcd/BulkStreamingMethodGPU.h
  hoomd/mpcd/CMakeLists.txt
  hoomd/mpcd/ConfinedStreamingMethodGPU.cu
  hoomd/mpcd/ParallelPlateGeometry.h
  hoomd/mpcd/ParallelPlateGeometryFiller.cc
  hoomd/mpcd/ParallelPlateGeometryFiller.h
  hoomd/mpcd/ParallelPlateGeometryFillerGPU.cc
  hoomd/mpcd/ParallelPlateGeometryFillerGPU.cu
  hoomd/mpcd/ParallelPlateGeometryFillerGPU.cuh
  hoomd/mpcd/ParallelPlateGeometryFillerGPU.h
  hoomd/mpcd/PlanarPoreGeometry.h
  hoomd/mpcd/PlanarPoreGeometryFiller.cc
  hoomd/mpcd/PlanarPoreGeometryFiller.h
  hoomd/mpcd/PlanarPoreGeometryFillerGPU.cc
  hoomd/mpcd/PlanarPoreGeometryFillerGPU.cu
  hoomd/mpcd/PlanarPoreGeometryFillerGPU.cuh
  hoomd/mpcd/PlanarPoreGeometryFillerGPU.h
  hoomd/mpcd/SlitGeometryFillerGPU.h
  hoomd/mpcd/StreamingGeometry.cc
  hoomd/mpcd/StreamingGeometry.h
  hoomd/mpcd/__init__.py
  hoomd/mpcd/geometry.py
  hoomd/mpcd/module.cc
  hoomd/mpcd/pytest/CMakeLists.txt
  hoomd/mpcd/pytest/test_geometry.py
  hoomd/mpcd/pytest/test_stream.py
  hoomd/mpcd/stream.py
  hoomd/mpcd/test/CMakeLists.txt
  hoomd/mpcd/test/parallel_plate_geometry_filler_mpi_test.cc
  hoomd/mpcd/test/parallel_plate_geometry_filler_test.cc
  hoomd/mpcd/test/planar_pore_geometry_filler_mpi_test.cc
  hoomd/mpcd/test/planar_pore_geometry_filler_test.cc
  hoomd/mpcd/test/streaming_method_test.cc
  sphinx-doc/module-mpcd-geometry.rst
  sphinx-doc/module-mpcd-stream.rst
  sphinx-doc/package-mpcd.rst
Labels: mpcd, validate

#1708 Remove GPUNotAvailableError from util
  hoomd/util.py
Labels: validate
