Repository glotzerlab/hoomd-blue, pull requests merged in 2024-11, with the labels that each got.

#1894 MPCD concentric cylinders geometry
  hoomd/mpcd/CMakeLists.txt
  hoomd/mpcd/ConcentricCylindersGeometry.cc
  hoomd/mpcd/ConcentricCylindersGeometry.h
  hoomd/mpcd/CosineChannelGeometry.h
  hoomd/mpcd/CosineExpansionContractionGeometry.h
  hoomd/mpcd/ParallelPlateGeometry.h
  hoomd/mpcd/PlanarPoreGeometry.h
  hoomd/mpcd/RejectionVirtualParticleFiller.h
  hoomd/mpcd/RejectionVirtualParticleFillerGPU.cuh
  hoomd/mpcd/SphereGeometry.h
  hoomd/mpcd/geometry.py
  hoomd/mpcd/module.cc
  hoomd/mpcd/pytest/test_geometry.py
  hoomd/mpcd/pytest/test_stream.py
  sphinx-doc/credits.rst
  sphinx-doc/module-mpcd-geometry.rst
Labels: mpcd, validate

#1926 Rename ``hoomd.hpmc.updater.Clusters`` to ``hoomd.hpmc.updater.GCA``.
  .pre-commit-config.yaml
  ARCHITECTURE.md
  CHANGELOG.rst
  example_plugins/shape_plugin/kernels.cu
  example_plugins/shape_plugin/module.cc
  hoomd/RNGIdentifiers.h
  hoomd/hpmc/CMakeLists.txt
  hoomd/hpmc/UpdaterGCA.h
  hoomd/hpmc/UpdaterGCAGPU.cu
  hoomd/hpmc/UpdaterGCAGPU.cuh
  hoomd/hpmc/UpdaterGCAGPU.h
  hoomd/hpmc/UpdaterGCAGPUDepletants.cuh
  hoomd/hpmc/kernel_cluster_depletants.cu.inc
  hoomd/hpmc/kernel_cluster_overlaps.cu.inc
  hoomd/hpmc/kernel_cluster_transform.cu.inc
  hoomd/hpmc/module.cc
  hoomd/hpmc/module_convex_polygon.cc
  hoomd/hpmc/module_convex_polyhedron.cc
  hoomd/hpmc/module_convex_spheropolyhedron.cc
  hoomd/hpmc/module_ellipsoid.cc
  hoomd/hpmc/module_faceted_ellipsoid.cc
  hoomd/hpmc/module_polyhedron.cc
  hoomd/hpmc/module_simple_polygon.cc
  hoomd/hpmc/module_sphere.cc
  hoomd/hpmc/module_spheropolygon.cc
  hoomd/hpmc/module_sphinx.cc
  hoomd/hpmc/module_union_convex_polyhedron.cc
  hoomd/hpmc/module_union_faceted_ellipsoid.cc
  hoomd/hpmc/module_union_sphere.cc
  hoomd/hpmc/pytest/CMakeLists.txt
  hoomd/hpmc/pytest/test_gca.py
  hoomd/hpmc/update.py
  sphinx-doc/features.rst
  sphinx-doc/migrating.rst
  sphinx-doc/module-hpmc-update.rst
Labels: validate, release

#1931 Remove the implicit depletant code path
  CHANGELOG.rst
  example_plugins/shape_plugin/ShapeMySphere.h
  example_plugins/shape_plugin/kernels.cu
  hoomd/RNGIdentifiers.h
  hoomd/hpmc/CMakeLists.txt
  hoomd/hpmc/ComputeFreeVolume.h
  hoomd/hpmc/ComputeFreeVolumeGPU.cuh
  hoomd/hpmc/HPMCCounters.h
  hoomd/hpmc/IntegratorHPMCMono.h
  hoomd/hpmc/IntegratorHPMCMonoGPU.h
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletants.cu
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletants.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsAuxilliaryPhase1.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsAuxilliaryPhase2.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsAuxilliaryTypes.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUDepletantsTypes.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUMoves.cuh
  hoomd/hpmc/IntegratorHPMCMonoGPUTypes.cuh
  hoomd/hpmc/Moves.h
  hoomd/hpmc/ShapeConvexPolygon.h
  hoomd/hpmc/ShapeConvexPolyhedron.h
  hoomd/hpmc/ShapeEllipsoid.h
  hoomd/hpmc/ShapeFacetedEllipsoid.h
  hoomd/hpmc/ShapePolyhedron.h
  hoomd/hpmc/ShapeSimplePolygon.h
  hoomd/hpmc/ShapeSphere.h
  hoomd/hpmc/ShapeSpheropolygon.h
  hoomd/hpmc/ShapeSpheropolyhedron.h
  hoomd/hpmc/ShapeSphinx.h
  hoomd/hpmc/ShapeUnion.h
  hoomd/hpmc/UpdaterGCA.h
  hoomd/hpmc/UpdaterGCAGPU.h
  hoomd/hpmc/UpdaterGCAGPUDepletants.cuh
  hoomd/hpmc/UpdaterMuVT.h
  hoomd/hpmc/compute.py
  hoomd/hpmc/integrate.py
  hoomd/hpmc/kernel_cluster_depletants.cu.inc
  hoomd/hpmc/kernel_depletants_auxilliary_phase1.cu.inc
  hoomd/hpmc/kernel_depletants_auxilliary_phase2.cu.inc
  hoomd/hpmc/kernel_insert_depletants.cu.inc
  hoomd/hpmc/module.cc
  hoomd/hpmc/pytest/test_shape.py
  hoomd/hpmc/update.py
  sphinx-doc/migrating.rst
Labels: validate, release

#1932 Remove TBB.
  .github/workflows/build_and_test.yaml
  .github/workflows/test.yaml
  .ignore
  BUILDING.rst
  CHANGELOG.rst
  CMake/hoomd/FindTBB.cmake
  CMakeLists.txt
  hoomd-config.cmake.in
  hoomd/CMakeLists.txt
  hoomd/ExecutionConfiguration.cc
  hoomd/ExecutionConfiguration.h
  hoomd/HOOMDMPI.h
  hoomd/HOOMDVersion.cc
  hoomd/HOOMDVersion.h.inc
  hoomd/device.py
  hoomd/hpmc/UpdaterGCA.h
  hoomd/module.cc
  hoomd/pytest/test_device.py
  hoomd/version.py
  sphinx-doc/migrating.rst
Labels: validate, release

#1934 Fix several issues with MPCD virtual particle filler on GPU
  CHANGELOG.rst
  hoomd/mpcd/RejectionVirtualParticleFiller.h
  hoomd/mpcd/RejectionVirtualParticleFillerGPU.cuh
  hoomd/mpcd/RejectionVirtualParticleFillerGPU.h
  hoomd/mpcd/module.cc
  hoomd/mpcd/pytest/test_fill.py
Labels: mpcd

#1941 Move wall and harmonic potentials to `external_potentials`.
  CHANGELOG.rst
  example_plugins/shape_plugin/module.cc
  hoomd/device.py
  hoomd/hpmc/CMakeLists.txt
  hoomd/hpmc/ExternalField.h
  hoomd/hpmc/ExternalFieldHarmonic.h
  hoomd/hpmc/ExternalFieldWall.h
  hoomd/hpmc/ExternalPotential.cc
  hoomd/hpmc/ExternalPotential.h
  hoomd/hpmc/ExternalPotentialLinear.cc
  hoomd/hpmc/ExternalPotentialLinear.h
  hoomd/hpmc/IntegratorHPMC.cc
  hoomd/hpmc/IntegratorHPMC.h
  hoomd/hpmc/IntegratorHPMCMono.h
  hoomd/hpmc/UpdaterBoxMC.cc
  hoomd/hpmc/UpdaterMuVT.h
  hoomd/hpmc/external/CMakeLists.txt
  hoomd/hpmc/external/__init__.py
  hoomd/hpmc/external/external.py
  hoomd/hpmc/external/field.py
  hoomd/hpmc/external/harmonic.py
  hoomd/hpmc/external/wall.py
  hoomd/hpmc/integrate.py
  hoomd/hpmc/module.cc
  hoomd/hpmc/module_convex_polygon.cc
  hoomd/hpmc/module_convex_polyhedron.cc
  hoomd/hpmc/module_convex_spheropolyhedron.cc
  hoomd/hpmc/module_ellipsoid.cc
  hoomd/hpmc/module_faceted_ellipsoid.cc
  hoomd/hpmc/module_polyhedron.cc
  hoomd/hpmc/module_simple_polygon.cc
  hoomd/hpmc/module_sphere.cc
  hoomd/hpmc/module_spheropolygon.cc
  hoomd/hpmc/module_sphinx.cc
  hoomd/hpmc/module_union_convex_polyhedron.cc
  hoomd/hpmc/module_union_faceted_ellipsoid.cc
  hoomd/hpmc/module_union_sphere.cc
  hoomd/hpmc/pytest/test_external_field.py
  hoomd/hpmc/pytest/test_external_wall.py
  hoomd/hpmc/pytest/test_muvt.py
  hoomd/update/remove_drift.py
  hoomd/wall.py
  sphinx-doc/features.rst
  sphinx-doc/howto/compute-the-free-energy-of-solids.rst
  sphinx-doc/migrating.rst
  sphinx-doc/module-hpmc-external-field.rst
  sphinx-doc/module-hpmc-external-wall.rst
  sphinx-doc/module-hpmc-external.rst
Labels: validate, release

#1953 Run `compute-sanitizer` on CI checks
  .github/workflows/build_and_test.yaml
  CHANGELOG.rst
  hoomd/md/VolumeConservationMeshForceComputeGPU.cu
Labels: validate

#1950 Allow triclinic boxes in MPCD
  CHANGELOG.rst
  hoomd/mpcd/CellList.cc
  hoomd/mpcd/CellList.h
  hoomd/mpcd/CellListGPU.cc
  hoomd/mpcd/CellListGPU.cu
  hoomd/mpcd/CellListGPU.cuh
  hoomd/mpcd/CellListGPU.h
  hoomd/mpcd/Communicator.cc
  hoomd/mpcd/CommunicatorGPU.cu
  hoomd/mpcd/ParallelPlateGeometryFiller.cc
  hoomd/mpcd/ParallelPlateGeometryFiller.h
  hoomd/mpcd/PlanarPoreGeometryFiller.cc
  hoomd/mpcd/PlanarPoreGeometryFiller.h
  hoomd/mpcd/RejectionVirtualParticleFiller.h
  hoomd/mpcd/RejectionVirtualParticleFillerGPU.h
  hoomd/mpcd/collide.py
  hoomd/mpcd/fill.py
  hoomd/mpcd/pytest/test_collide.py
  hoomd/mpcd/test/cell_communicator_mpi_test.cc
  hoomd/mpcd/test/cell_list_mpi_test.cc
  hoomd/mpcd/test/cell_list_test.cc
  hoomd/mpcd/test/parallel_plate_geometry_filler_test.cc
  hoomd/mpcd/test/planar_pore_geometry_filler_test.cc
  hoomd/mpcd/test/utils.h
Labels: mpcd

#1897 Fix segfaults for MPCD with large particle counts under MPI
  CHANGELOG.rst
  hoomd/Communicator.cc
  hoomd/HOOMDMPI.h
  hoomd/MPIConfiguration.cc
  hoomd/MPIConfiguration.h
  hoomd/SnapshotSystemData.cc
  hoomd/mpcd/Communicator.cc
  hoomd/mpcd/Communicator.h
  hoomd/mpcd/CommunicatorGPU.cc
  hoomd/mpcd/ParticleData.cc
  hoomd/mpcd/ParticleData.h
  hoomd/mpcd/ParticleDataSnapshot.cc
  hoomd/mpcd/ParticleDataSnapshot.h
  hoomd/mpcd/VirtualParticleFiller.cc
Labels: mpcd, validate
