Repository glotzerlab/hoomd-blue, pull requests merged in 2024-06, with the labels that each got.

#1797 Update CI test matrix and support numpy 2.0.
  .github/workflows/release.yml
  .github/workflows/templates/configurations.yml
  .github/workflows/templates/workflow.yml
  .github/workflows/test.yml
  BUILDING.rst
  CMake/hoomd/HOOMDPythonSetup.cmake
  hoomd-config.cmake.in
  hoomd/md/pytest/test_custom_force.py
Labels: validate, release

#1800 Small docfix: fix namespace error in example in md.force.Custom docstring
  hoomd/md/force.py
Labels: validate

#1803 Provide full CUDA errors for device scan messages.
  hoomd/ExecutionConfiguration.cc
Labels: validate

#1798 Refactor CI workflows
  .github/dependabot.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/make_workflows.py
  .github/workflows/release.yaml
  .github/workflows/release.yml
  .github/workflows/stale.yaml
  .github/workflows/stale.yml
  .github/workflows/templates/configurations.yml
  .github/workflows/templates/release.yml
  .github/workflows/templates/test.yml
  .github/workflows/templates/workflow.yml
  .github/workflows/test.yaml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  BUILDING.rst
  hoomd/Communicator.cc
  hoomd/CommunicatorGPU.cc
  hoomd/HOOMDMPI.h
  hoomd/LoadBalancer.cc
  hoomd/VectorMath.h
  hoomd/hpmc/MinkowskiMath.h
  hoomd/hpmc/ShapeConvexPolyhedron.h
  hoomd/hpmc/ShapeUnion.h
  hoomd/hpmc/UpdaterMuVT.h
  hoomd/hpmc/XenoCollide3D.h
  hoomd/md/NeighborList.cc
  hoomd/md/PotentialExternal.h
  hoomd/md/PotentialTersoff.h
  hoomd/mpcd/test/communicator_mpi_test.cc
Labels: validate, release

#1813 Restrict `mpcd.collide.CellList` cell size
  hoomd/mpcd/collide.py
  hoomd/mpcd/integrate.py
  sphinx-doc/migrating.rst
Labels: mpcd, validate

#1820 Improve the data access error message.
  hoomd/error.py
Labels: validate

#1821 Fix "Failed to get a function signature" sphinx warnings.
  hoomd/custom/custom_operation.py
Labels: validate

#1816 Use conda lock files and micromamba in place of docker images
  .github/workflows/build_and_test.yaml
  .github/workflows/environments/environment.yaml
  .github/workflows/environments/py310-conda-lock.yml
  .github/workflows/environments/py311-conda-lock.yml
  .github/workflows/environments/py312-conda-lock.yml
  .github/workflows/environments/py39-conda-lock.yml
  .github/workflows/environments/update-lockfiles.sh
  .github/workflows/test.yaml
  ARCHITECTURE.md
  BUILDING.rst
  sphinx-doc/testing.rst
Labels: validate, release

#1823 Fix misc CI issues.
  .github/workflows/build_and_test.yaml
Labels: validate, release

#1810 Enhancement/md pair gaussian value check
  hoomd/md/pair/pair.py
  hoomd/md/pytest/test_potential.py
  sphinx-doc/credits.rst
Labels: validate

#1825 fix Brownian integrators when using anisotropic interactions and zeroing out elements of the moment of inertia tensor
  hoomd/md/TwoStepBD.cc
  hoomd/md/TwoStepBDGPU.cu
  hoomd/md/TwoStepRATTLEBD.h
  hoomd/md/TwoStepRATTLEBDGPU.cuh
Labels: validate
